server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-docs-route
          uri: lb://kahala
          predicates:
            - Path=/kahala/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
          metadata:
            swaggerDocs: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/
